### PR TITLE
Solve the problem of concurrency

### PR DESCRIPTION
**Pull request by chenhuawei**
Serialization of the same function

### CODE REVIEW

**Comment by hacker-cb** [comment]
I don't have possibility to test it because I'm not working with modbus now.

@chenhuawei Seems you are working with modbus more than me now. 
Are you sure with your code? 
I  can merge and publish new release if you are 100% sure.

**Comment by chenhuawei** [comment]
> I don't have possibility to test it because I'm not working with modbus now.
> 
> @chenhuawei Seems you are working with modbus more than me now. Are you sure with your code? I can merge and publish new release if you are 100% sure.

I've already tested it with the simulator.
Random writes are performed while reading registers at a high frequency.
So I think I can be 100% sure.

**Comment by hacker-cb** [comment]
Ok, thank you for your work

**Comment by hacker-cb** [comment]
Published 0.2.0 to pub

**Pull request merged**
